### PR TITLE
Use Beastiary

### PR DESCRIPTION
**Pull request by Wytamma**
Hi Enzo!

This is a great idea :) I've been working on [beastiary](https://beastiary.wytamma.com/) and think it could work well in your project. So, I added the changes here.

Here's the version with beastiary: 
https://colab.research.google.com/github/Wytamma/ColabBEAST/blob/main/BEAST2.ipynb

### CODE REVIEW

**Comment by EnzoAndree** [comment]
Hello, what a wonderful visualisation tool. Thanks for sharing this piece of code.

I think there is a package missing in the installation. 

`!pip install pyngrok`

Do you think it is possible to display multiple chains of an analysis on the same graph? currently, it only shows one at a time.

Another comment on your implementation. I think it is useful for the analysis to remove the first states (aka. Burn-in). This allows increasing the scale automatically to evaluate the mixture and convergence at a quick glance. Since you can't see the classic caterpillar hair-like plot with the default scale. In my implementation, I remove the first 10% of the states and it looks good, but I think you could go one step further and let the user define in Beastiary a Burn-in dynamically.

image
image

Have you explored the possibility of calculating EES natively in Beastiary? that would be amazing, but I was not able to implement it in this version of GoogleColab.

By the way, Beastiary works like magic! great job!

**Comment by Wytamma** [comment]
Thanks for the suggestions! I plan to implement them all by version 1.0 (https://github.com/Wytamma/beastiary/projects/1). Ah, the pyngrok import isn't needed and I have removed it :)

**Comment by Wytamma** [comment]
Hey @EnzoAndree, Just to let you know I've now released beastiary v1.0 and it has all the features you requested above. Let me know what you think / if there's anything I should changed.

-W

**Comment by EnzoAndree** [comment]
Hello Wytamma!

Sorry for the delay, it's been a tough few days since your pull request.
Now beastiary looks amazing!

I will do the merge and save the previous version as BEAST2_old.ipynb 

A couple of days ago I tried to make colab automatically end the execution of beastiary when BEAST finishes. But without success. Any idea how to implement that?

Again, great work with beastiary!

**Comment by Wytamma** [comment]
Cool thanks! 

I guess it depends why you want to stop bestiary? If you want to run the download cell after beast finishes, you could background the `!lt --port $PORT --subdomain beastiary` call then write a loop that sleeps until all the beast PIDs finish?

**Pull request merged**
